export const BOOKING_PAYMENT_REQUEST = "BOOKING_PAYMENT_REQUEST";
export const BOOKING_PAYMENT_SUCCESS = "BOOKING_PAYMENT_SUCCESS";
export const BOOKING_PAYMENT_FAIL = "BOOKING_PAYMENT_FAIL";
export const BOOKING_PAYMENT_RESET = "BOOKING_PAYMENT_RESET";


export const USER_BOOKING_REQUEST = "USER_BOOKING_REQUEST";
export const USER_BOOKING_SUCCESS = "USER_BOOKING_SUCCESS";
export const USER_BOOKING_FAIL = "USER_BOOKING_FAIL";