export const BOOKING_PAYMENT_REQUEST = "BOOKING_PAYMENT_REQUEST";
export const BOOKING_PAYMENT_SUCCESS = "BOOKING_PAYMENT_SUCCESS";
export const BOOKING_PAYMENT_FAIL = "BOOKING_PAYMENT_FAIL";
export const BOOKING_PAYMENT_RESET = "BOOKING_PAYMENT_RESET";
