export const GET_TOP_TOURS_REQUEST = "GET_TOP_TOURS_REQUEST";
export const GET_TOP_TOURS_SUCCESS = "GET_TOP_TOURS_SUCCESS";
export const GET_TOP_TOURS_FAIL = "GET_TOP_TOURS_FAIL";

export const GET_TOURS_REQUEST = "GET_TOURS_REQUEST";
export const GET_TOURS_SUCCESS = "GET_TOURS_SUCCESS";
export const GET_TOURS_FAIL = "GET_TOURS_FAIL";

export const GET_TOURS_DETAILS_REQUEST = "GET_TOURS_DETAILS_REQUEST";
export const GET_TOURS_DETAILS_SUCCESS = "GET_TOURS_DETAILS_SUCCESS";
export const GET_TOURS_DETAILS_FAIL = "GET_TOURS_DETAILS_FAIL";

export const GET_TOUR_DETAILS_REQUEST = "GET_TOUR_DETAILS_REQUEST";
export const GET_TOUR_DETAILS_SUCCESS = "GET_TOUR_DETAILS_SUCCESS";
export const GET_TOUR_DETAILS_FAIL = "GET_TOUR_DETAILS_FAIL";

export const TOUR_CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const TOUR_CREATE_REVIEW_SUCCESS = "TOUR_CREATE_REVIEW_SUCCESS";
export const TOUR_CREATE_REVIEW_FAIL = "TOUR_CREATE_REVIEW_FAIL";
export const TOUR_CREATE_REVIEW_RESET = "TOUR_CREATE_REVIEW_RESET";
